### ISSUE TITLE
Windows install/cant boot

### ISSUE THREAD

**Issue by Kokkolabs** [gnodipac886/MatebookXPro-hackintosh#24]
All goes well, but after "reinstall osx" it reboot but only on usb?
What happened on install?

**Comment by Kokkolabs** [comment]
Got installed, couple times testing.
Now boot install from ssd, but via bootloop :)

**Comment by gnodipac886** [comment]
I'm not sure I'm understanding. What is the issue right now?

**Comment by Talal916** [comment]
Copy the Clover .efi file to the Microsoft Boot folder, and rename it to bootmgfw.efi. Rename the original bootmgfw.efi to bootmgfw-orig.efi

**Comment by sebpalluel** [comment]
Yes, it happen at every Windows Update -that is done behind the scene-. Windows kind of overwrite the bootloader of Clover with his own. That's why you need to rename `bootmgfw.efi` to `bootmgfw-orig.efi`.
You can resolve this issue definitively by following the steps described here : https://www.insanelymac.com/forum/topic/326494-how-to-make-clover-default-bootloader-after-installing-windows-on-uefi/

**Comment by Kokkolabs** [comment]
All problems was my ssd PM981, i order evo 970.
Testing again when its arrived.
