### ISSUE TITLE
支持白果的手势吗？在犹豫购买

### ISSUE THREAD

**Issue by abc3436645** [gnodipac886/MatebookXPro-hackintosh#28]

**Comment by RoderickQiu** [comment]
支持，但是不是很好。
容易识别不了。
同样，触摸屏可以识别，但也同样用不爽。

但是这个机器本身是很值得推荐的。但如果用macOS作为主力系统的话不很合适。（除了少数深度适配的黑果台式机，别的其实都不合适作为主力。）

**Comment by abc3436645** [comment]
感谢您的意见，目前是习惯的macOS，感觉回不去了。本身有一台黑苹果是通过外接trackpad完美支持白果手势，但是是通过线连接实现，蓝牙连接不上。

**Comment by RoderickQiu** [comment]
按照现在这个repo的方法搞，基本就是无线网络废了，独显废了，蓝牙有概率成功。我个人使用的时候是插着手机用HoRNDIS供网。

的确觉得macOS很不错，但是因为一些原因，主力Win10，开发需求用macOS。触控板平时用macOS时候也用，只不过体验就像9012年用非精准触控板一样。

**Comment by abc3436645** [comment]
按照目前这个状态的话，如果x pro上独显版很多功能不完美的话，这个价格还是推荐上白果了，感觉还是matebook13 matebook14搞黑果性价比比较高

**Comment by dimon222** [comment]
Sadly, MacOS is quite buggy on this machine, and has broken wifi (internal Intel driver is proprietary and doesn't have variant for MacOS). You can achieve somewhat working experience with some tunings and external wifi adapter, but its obviously not same experience as pure Macbook.

If u want native experience, desktop variants of Hackintosh a more stable. Alternatively, you can use Linux instead of MacOS (which i found much more stable - Manjaro/Arch) with support everything you need in this laptop. Touchpad experience is still not comparable to Macbook, so you can't really expect it tho.
