### ISSUE TITLE
No 5Ghz WiFi speed with Edimax AC1200 (EW-7822ULC)

### ISSUE THREAD

**Issue by vblinden** [gnodipac886/MatebookXPro-hackintosh#90]
Hello everyone,

First thanks for making the process of installing macOS Catalina on the Matebook X Pro so easy. I bought the Edimax AC1200 (EW-7822ULC) to have Wireless Internet on my laptop. But I can't connect with a 5Ghz network.

I installed the driver version 1.0.2.0 from [here](https://www.edimax.com/edimax/download/download/data/edimax/global/download/for_home/wireless_adapters/wireless_adapters_ac1200_dual-band/ew-7822ulc), is this  the correct one? I can only connect to 2.4Ghz networks.

What am I doing wrong?

**Comment by Chatbox1024** [comment]
Try this: https://github.com/chris1111/Wireless-USB-Adapter

**Comment by vblinden** [comment]
I have also installed the chris1111 driver but I also can only connect to a 2.4Ghz network and not with a 5Ghz network. My phone can connect to both with no problem. Is there a setting I have to set?

**Comment by gnodipac886** [comment]
Nope, it just doesn't support it.

**Comment by vblinden** [comment]
@gnodipac886, you mean the adapter doesn't support it or the driver doesn't support it?

**Comment by kmonty** [comment]
@vblinden the hardware doesn't support 5Ghz. Recommend upgrading to a tp-link nano if you want to use both bands.

**Comment by Chatbox1024** [comment]
@vblinden, FYI, I'm using an Asus USB-AC53 Nano, and it seems to work well (has both 2.4 and 5.0GHz bands)

**Comment by vblinden** [comment]
Thanks @Chatbox1024, @kmonty and @gnodipac886

**Comment by Chatbox1024** [comment]
Strange / Funny: I uninstalled the Chris1111's wifi driver, and thought I'll give the EW-7822ULC v1.0.2.0 driver a try because Chris1111's driver was dropping out (and I know it's not an issue between the AC53 Nano and my AP because I use them on the same laptop under Windows and Linux without issue...which pointed me to potentially driver related).

Well well, what do you know....the v1.0.2.0 driver works VERY well with my AC53 Nano, and it's a signed driver.

Just thought I'll add this info here for those who might be wondering.
